version: "3"
services:
  node:
    build: ./docker
    user: "node"
    command: sleep infinity
    # command: "npm start"
    working_dir: /usr/src/app
    # environment:
    #   - NODE_ENV=production
    expose:
      - "8080"
    volumes:
      - ./app:/usr/src/app