# node - Docker Hub
# https://hub.docker.com/_/node/

# nodejs/docker-node: Official Docker Image for Node.js
# https://github.com/nodejs/docker-node

FROM node:12.16.3-stretch

RUN npm install webpack webpack-cli gulp http-server -g